version: "3.8"
services:
  proxy:
    image: nginx:latest
    hostname: proxy
    read_only: true
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /Volumes/WORKING/training/docker/demo-communication/tmp:/tmp
      - /Volumes/WORKING/training/docker/demo-communication/proxy/cache:/var/cache/nginx
      - /Volumes/WORKING/training/docker/demo-communication/proxy/run:/var/run
      - /Volumes/WORKING/training/docker/demo-communication/proxy/nginx.conf:/etc/nginx/nginx.conf
      - /Volumes/WORKING/training/docker/demo-communication/proxy/log/nginx:/var/log/nginx
      - /Volumes/WORKING/training/docker/demo-communication/proxy/cert:/etc/nginx/cert
    networks:
      dmz-net:
      external-net:
  app:
    image: openjdk:11.0.7-jdk
    read_only: true
    hostname: app
    expose:
      - 9090
    environment:
      DEMO_HOME: /opt/demo-communication
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - /Volumes/WORKING/training/docker/demo-communication/tmp:/tmp
      - /Volumes/WORKING/training/docker/demo-communication/app/opt:/opt/demo-communication
    depends_on:
      - proxy
    networks:
      internal-net:
      dmz-net:
    labels:
      # for enterprise ver: domain+port for a services cluster
      com.docker.lb.hosts: demo_comm_app
      com.docker.lb.port: 9090
    command: java -jar /opt/demo-communication/demo-communication-web-1.0-SNAPSHOT.war
networks:
  internal-net:
    internal: true
    name: internal-net
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/24"
  dmz-net:
    internal: true
    name: dmz-net
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
  external-net:
    name: external-net